// auto generated by go tool dist

package sys

const DefaultGoroot = `/usr/local/go`
const TheVersion = `devel +111d590 Fri Jul 29 01:09:55 2016 +0000`
const Goexperiment = ``
const StackGuardMultiplier = 1

